# Generated by Django 4.2.30 on 2026-06-17 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0002_instrumentquestion_requireddocumenttype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiagaStatusSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('BELUM_DIBINA', 'Belum Dibina'), ('MENUNGGU_REVIEW', 'Menunggu Review'), ('SYARAT_BELUM_TERPENUHI', 'Syarat Belum Terpenuhi'), ('SIAP_DIVALIDASI', 'Siap Divalidasi')], db_index=True, max_length=40)),
                ('mgmp_count', models.PositiveSmallIntegerField(default=0)),
                ('is_eligible', models.BooleanField(db_index=True, default=False)),
                ('note', models.TextField(blank=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siaga_snapshots', to='master.gurubinaan')),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siaga_snapshots', to='master.tahunajaran')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tahun_ajaran', 'status'], name='dashboard_s_tahun_a_693c58_idx')],
                'unique_together': {('guru', 'tahun_ajaran')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error')], db_index=True, default='INFO', max_length=20)),
                ('channel', models.CharField(choices=[('IN_APP', 'In App'), ('WHATSAPP', 'WhatsApp')], db_index=True, default='IN_APP', max_length=20)),
                ('target_url', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='dashboard_n_recipie_344987_idx'), models.Index(fields=['channel', 'sent_at'], name='dashboard_n_channel_b63434_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonitoringSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission_type', models.CharField(db_index=True, max_length=10)),
                ('submission_status', models.CharField(db_index=True, max_length=20)),
                ('document_total', models.PositiveIntegerField(default=0)),
                ('document_reviewed', models.PositiveIntegerField(default=0)),
                ('document_revisi', models.PositiveIntegerField(default=0)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_snapshots', to='master.gurubinaan')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_snapshots', to='master.periodetriwulan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['periode', 'submission_status'], name='dashboard_m_periode_4472f0_idx')],
                'unique_together': {('guru', 'periode', 'submission_type')},
            },
        ),
    ]
