# Generated by Django 4.2.30 on 2026-06-17 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0002_instrumentquestion_requireddocumenttype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission_type', models.CharField(db_index=True, max_length=10)),
                ('submission_id', models.PositiveBigIntegerField(db_index=True)),
                ('revision_number', models.PositiveIntegerField(default=1)),
                ('note_admin', models.TextField()),
                ('note_guru', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='master.gurubinaan')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='master.periodetriwulan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['guru', 'periode', 'is_resolved'], name='dokumen_sub_guru_id_88eb83_idx')],
                'unique_together': {('submission_type', 'submission_id', 'revision_number')},
            },
        ),
        migrations.CreateModel(
            name='SubmissionReviewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission_type', models.CharField(db_index=True, max_length=10)),
                ('submission_id', models.PositiveBigIntegerField(db_index=True)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(db_index=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_histories', to='master.gurubinaan')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_histories', to='master.periodetriwulan')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_reviews', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['submission_type', 'submission_id'], name='dokumen_sub_submiss_780998_idx'), models.Index(fields=['guru', 'periode'], name='dokumen_sub_guru_id_e0f3c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubmissionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_submission', models.CharField(choices=[('TW1', 'TW1'), ('TW2', 'TW2'), ('TW3', 'TW3'), ('TW4', 'TW4')], db_index=True, max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='submission/documents/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('is_video', models.BooleanField(db_index=True, default=False)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending'), ('LENGKAP', 'Lengkap'), ('REVISI', 'Perlu Revisi')], db_index=True, default='PENDING', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='master.gurubinaan')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='master.periodetriwulan')),
                ('required_document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='master.requireddocumenttype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['guru', 'periode'], name='dokumen_sub_guru_id_de13aa_idx'), models.Index(fields=['target_submission', 'review_status'], name='dokumen_sub_target__827613_idx')],
            },
        ),
    ]
