# Generated by Django 4.2.30 on 2026-06-17 03:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_approval_note_customuser_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationrequest',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
