# Generated by Django 6.0.6 on 2026-06-17 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionTW3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_review', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVISI', 'Perlu Revisi'), ('LENGKAP', 'Lengkap')], default='DRAFT', max_length=20)),
                ('feedback_admin', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jml_kehadiran', models.IntegerField(default=0)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.gurubinaan')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.periodetriwulan')),
            ],
            options={
                'unique_together': {('guru', 'periode')},
            },
        ),
    ]
