# Generated by Django 4.2.30 on 2026-06-17 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0002_instrumentquestion_requireddocumenttype_and_more'),
        ('triwulan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionTW1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_review', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVISI', 'Perlu Revisi'), ('LENGKAP', 'Lengkap')], db_index=True, default='DRAFT', max_length=20)),
                ('feedback_admin', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('status_sekolah', models.CharField(blank=True, max_length=30)),
                ('kelengkapan_mengajar', models.JSONField(blank=True, default=list)),
                ('q12', models.CharField(blank=True, max_length=1)),
                ('q13', models.CharField(blank=True, max_length=1)),
                ('q14', models.CharField(blank=True, max_length=1)),
                ('q15', models.CharField(blank=True, max_length=1)),
                ('q16', models.CharField(blank=True, max_length=1)),
                ('q17', models.CharField(blank=True, max_length=1)),
                ('q18', models.CharField(blank=True, max_length=1)),
                ('q19', models.CharField(blank=True, max_length=1)),
                ('q20', models.CharField(blank=True, max_length=1)),
                ('q21', models.CharField(blank=True, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionTW2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_review', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVISI', 'Perlu Revisi'), ('LENGKAP', 'Lengkap')], db_index=True, default='DRAFT', max_length=20)),
                ('feedback_admin', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('link_video_youtube', models.URLField(blank=True)),
                ('model_pembelajaran', models.TextField(blank=True)),
                ('catatan_metakognitif', models.TextField(blank=True)),
                ('q22', models.CharField(blank=True, max_length=1)),
                ('q23', models.CharField(blank=True, max_length=1)),
                ('q24', models.CharField(blank=True, max_length=1)),
                ('q25', models.CharField(blank=True, max_length=1)),
                ('q26', models.CharField(blank=True, max_length=1)),
                ('q27', models.CharField(blank=True, max_length=1)),
                ('q28', models.CharField(blank=True, max_length=1)),
                ('q29', models.CharField(blank=True, max_length=1)),
                ('q30', models.CharField(blank=True, max_length=1)),
                ('q31', models.CharField(blank=True, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionTW4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_review', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVISI', 'Perlu Revisi'), ('LENGKAP', 'Lengkap')], db_index=True, default='DRAFT', max_length=20)),
                ('feedback_admin', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('skor_karakter', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('indikator_json', models.JSONField(blank=True, default=dict)),
                ('q42', models.CharField(blank=True, max_length=1)),
                ('q43', models.CharField(blank=True, max_length=1)),
                ('q44', models.CharField(blank=True, max_length=1)),
                ('q45', models.CharField(blank=True, max_length=1)),
                ('q46', models.CharField(blank=True, max_length=1)),
                ('q47', models.CharField(blank=True, max_length=1)),
                ('q48', models.CharField(blank=True, max_length=1)),
                ('q49', models.CharField(blank=True, max_length=1)),
                ('q50', models.CharField(blank=True, max_length=1)),
                ('q51', models.CharField(blank=True, max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='submissiontw3',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='submissiontw3',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissiontw3',
            name='q32',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='submissiontw3',
            name='q33',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='submissiontw3',
            name='q34',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='submissiontw3',
            name='q35',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='submissiontw3',
            name='q36',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='submissiontw3',
            name='q37',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='submissiontw3',
            name='q38',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='submissiontw3',
            name='q39',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='submissiontw3',
            name='q40',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='submissiontw3',
            name='q41',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='submissiontw3',
            name='resume_pembinaan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submissiontw3',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submissiontw3',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submissiontw3',
            name='guru',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='master.gurubinaan'),
        ),
        migrations.AlterField(
            model_name='submissiontw3',
            name='jml_kehadiran',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 Kali'), (2, '2 Kali'), (3, '3 Kali'), (4, 'Lebih dari 3 Kali')], default=1),
        ),
        migrations.AlterField(
            model_name='submissiontw3',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='master.periodetriwulan'),
        ),
        migrations.AlterField(
            model_name='submissiontw3',
            name='status_review',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVISI', 'Perlu Revisi'), ('LENGKAP', 'Lengkap')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='submissiontw3',
            index=models.Index(fields=['guru', 'periode'], name='triwulan_su_guru_id_ed066b_idx'),
        ),
        migrations.AddIndex(
            model_name='submissiontw3',
            index=models.Index(fields=['status_review'], name='triwulan_su_status__eac672_idx'),
        ),
        migrations.AddField(
            model_name='submissiontw4',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissiontw4',
            name='guru',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='master.gurubinaan'),
        ),
        migrations.AddField(
            model_name='submissiontw4',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='master.periodetriwulan'),
        ),
        migrations.AddField(
            model_name='submissiontw4',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissiontw2',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissiontw2',
            name='guru',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='master.gurubinaan'),
        ),
        migrations.AddField(
            model_name='submissiontw2',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='master.periodetriwulan'),
        ),
        migrations.AddField(
            model_name='submissiontw2',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissiontw1',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissiontw1',
            name='guru',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='master.gurubinaan'),
        ),
        migrations.AddField(
            model_name='submissiontw1',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='master.periodetriwulan'),
        ),
        migrations.AddField(
            model_name='submissiontw1',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='submissiontw4',
            index=models.Index(fields=['guru', 'periode'], name='triwulan_su_guru_id_f41468_idx'),
        ),
        migrations.AddIndex(
            model_name='submissiontw4',
            index=models.Index(fields=['status_review'], name='triwulan_su_status__f5016b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submissiontw4',
            unique_together={('guru', 'periode')},
        ),
        migrations.AddIndex(
            model_name='submissiontw2',
            index=models.Index(fields=['guru', 'periode'], name='triwulan_su_guru_id_c56a0a_idx'),
        ),
        migrations.AddIndex(
            model_name='submissiontw2',
            index=models.Index(fields=['status_review'], name='triwulan_su_status__0b71ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submissiontw2',
            unique_together={('guru', 'periode')},
        ),
        migrations.AddIndex(
            model_name='submissiontw1',
            index=models.Index(fields=['guru', 'periode'], name='triwulan_su_guru_id_edc350_idx'),
        ),
        migrations.AddIndex(
            model_name='submissiontw1',
            index=models.Index(fields=['status_review'], name='triwulan_su_status__1a195f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submissiontw1',
            unique_together={('guru', 'periode')},
        ),
    ]
