ROLE_ADMIN = "ADMIN"
ROLE_GURU = "GURU"

ROLE_CHOICES = [
    (ROLE_ADMIN, "Admin"),
    (ROLE_GURU, "Guru"),
]

ACCOUNT_STATUS_PENDING = "PENDING"
ACCOUNT_STATUS_ACTIVE = "ACTIVE"
ACCOUNT_STATUS_SUSPENDED = "SUSPENDED"
ACCOUNT_STATUS_REJECTED = "REJECTED"

ACCOUNT_STATUS_CHOICES = [
    (ACCOUNT_STATUS_PENDING, "Pending"),
    (ACCOUNT_STATUS_ACTIVE, "Active"),
    (ACCOUNT_STATUS_SUSPENDED, "Suspended"),
    (ACCOUNT_STATUS_REJECTED, "Rejected"),
]

REVIEW_STATUS_DRAFT = "DRAFT"
REVIEW_STATUS_SUBMITTED = "SUBMITTED"
REVIEW_STATUS_REVISI = "REVISI"
REVIEW_STATUS_LENGKAP = "LENGKAP"

REVIEW_STATUS_CHOICES = [
    (REVIEW_STATUS_DRAFT, "Draft"),
    (REVIEW_STATUS_SUBMITTED, "Submitted"),
    (REVIEW_STATUS_REVISI, "Perlu Revisi"),
    (REVIEW_STATUS_LENGKAP, "Lengkap"),
]

NOTIFICATION_IN_APP = "IN_APP"
NOTIFICATION_WA = "WHATSAPP"

NOTIFICATION_CHANNEL_CHOICES = [
    (NOTIFICATION_IN_APP, "In App"),
    (NOTIFICATION_WA, "WhatsApp"),
]

NOTIFICATION_INFO = "INFO"
NOTIFICATION_SUCCESS = "SUCCESS"
NOTIFICATION_WARNING = "WARNING"
NOTIFICATION_ERROR = "ERROR"

NOTIFICATION_LEVEL_CHOICES = [
    (NOTIFICATION_INFO, "Info"),
    (NOTIFICATION_SUCCESS, "Success"),
    (NOTIFICATION_WARNING, "Warning"),
    (NOTIFICATION_ERROR, "Error"),
]

SIAGA_BELUM_DIBINA = "BELUM_DIBINA"
SIAGA_MENUNGGU_REVIEW = "MENUNGGU_REVIEW"
SIAGA_SYARAT_BELUM_TERPENUHI = "SYARAT_BELUM_TERPENUHI"
SIAGA_SIAP_DIVALIDASI = "SIAP_DIVALIDASI"

SIAGA_STATUS_CHOICES = [
    (SIAGA_BELUM_DIBINA, "Belum Dibina"),
    (SIAGA_MENUNGGU_REVIEW, "Menunggu Review"),
    (SIAGA_SYARAT_BELUM_TERPENUHI, "Syarat Belum Terpenuhi"),
    (SIAGA_SIAP_DIVALIDASI, "Siap Divalidasi"),
]