# Generated by Django 6.0.6 on 2026-06-17 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SekolahBinaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sekolah', models.CharField(max_length=255)),
                ('jenjang', models.CharField(choices=[('SMA', 'SMA'), ('SMK', 'SMK')], max_length=10)),
                ('status', models.CharField(choices=[('N', 'Negeri'), ('S', 'Swasta')], max_length=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nama_sekolah'],
            },
        ),
        migrations.CreateModel(
            name='TahunAjaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuruBinaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('nip_siaga', models.CharField(blank=True, max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guru_profile', to=settings.AUTH_USER_MODEL)),
                ('sekolah', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gurus', to='master.sekolahbinaan')),
            ],
            options={
                'ordering': ['nama_lengkap'],
            },
        ),
        migrations.CreateModel(
            name='PeriodeTriwulan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.IntegerField(choices=[(1, 'Triwulan I'), (2, 'Triwulan II'), (3, 'Triwulan III'), (4, 'Triwulan IV')])),
                ('tema', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('is_open', models.BooleanField(default=False)),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes', to='master.tahunajaran')),
            ],
            options={
                'ordering': ['tahun_ajaran', 'nomor'],
                'unique_together': {('tahun_ajaran', 'nomor')},
            },
        ),
    ]
