# Generated by Django 4.2.30 on 2026-06-17 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10)),
                ('label', models.TextField()),
                ('question_type', models.CharField(choices=[('PILIHAN', 'Pilihan A/B/C/D'), ('TEXT', 'Text'), ('NUMBER', 'Number'), ('BOOLEAN', 'Boolean')], default='PILIHAN', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RequiredDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('allowed_extensions', models.CharField(blank=True, help_text='Contoh: pdf,jpg,png,zip', max_length=255)),
                ('max_size_mb', models.PositiveIntegerField(default=10)),
                ('is_required', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.AlterModelOptions(
            name='periodetriwulan',
            options={'ordering': ['tahun_ajaran__label', 'nomor']},
        ),
        migrations.AddField(
            model_name='gurubinaan',
            name='akun_siaga',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gurubinaan',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gurubinaan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gurubinaan',
            name='golongan',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gurubinaan',
            name='nik',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='gurubinaan',
            name='nip',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='gurubinaan',
            name='nomor_wa',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='gurubinaan',
            name='satminkal',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gurubinaan',
            name='status_sertifikasi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gurubinaan',
            name='tahun_ajaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guru_binaan', to='master.tahunajaran'),
        ),
        migrations.AddField(
            model_name='gurubinaan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gurubinaan',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='periodetriwulan',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='periodetriwulan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='periodetriwulan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='periodetriwulan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='periodetriwulan',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sekolahbinaan',
            name='alamat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sekolahbinaan',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sekolahbinaan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sekolahbinaan',
            name='npsn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sekolahbinaan',
            name='slug',
            field=models.SlugField(blank=True, max_length=280, unique=True),
        ),
        migrations.AddField(
            model_name='sekolahbinaan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sekolahbinaan',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tahunajaran',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tahunajaran',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tahunajaran',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tahunajaran',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tahunajaran',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gurubinaan',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='gurubinaan',
            name='nip_siaga',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='gurubinaan',
            name='sekolah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gurus', to='master.sekolahbinaan'),
        ),
        migrations.AlterField(
            model_name='periodetriwulan',
            name='is_open',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='periodetriwulan',
            name='nomor',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Triwulan I — Perencanaan & Pemetaan'), (2, 'Triwulan II — Pendampingan Tahap Awal'), (3, 'Triwulan III — Observasi & Umpan Balik'), (4, 'Triwulan IV — Evaluasi & Pelaporan')]),
        ),
        migrations.AlterField(
            model_name='periodetriwulan',
            name='tahun_ajaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periodes', to='master.tahunajaran'),
        ),
        migrations.AlterField(
            model_name='sekolahbinaan',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='sekolahbinaan',
            name='jenjang',
            field=models.CharField(choices=[('SMA', 'SMA'), ('SMK', 'SMK')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='sekolahbinaan',
            name='nama_sekolah',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sekolahbinaan',
            name='status',
            field=models.CharField(choices=[('N', 'Negeri'), ('S', 'Swasta')], db_index=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='tahunajaran',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tahunajaran',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='gurubinaan',
            index=models.Index(fields=['tahun_ajaran', 'sekolah'], name='master_guru_tahun_a_c87b58_idx'),
        ),
        migrations.AddIndex(
            model_name='gurubinaan',
            index=models.Index(fields=['tahun_ajaran', 'is_active'], name='master_guru_tahun_a_47b591_idx'),
        ),
        migrations.AddField(
            model_name='requireddocumenttype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requireddocumenttype',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_document_types', to='master.periodetriwulan'),
        ),
        migrations.AddField(
            model_name='requireddocumenttype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instrumentquestion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instrumentquestion',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='master.periodetriwulan'),
        ),
        migrations.AddField(
            model_name='instrumentquestion',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='requireddocumenttype',
            unique_together={('periode', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='instrumentquestion',
            unique_together={('periode', 'code')},
        ),
    ]
